<?php

namespace AppBundle\Repository;

/**
 * AddProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddProductRepository extends \Doctrine\ORM\EntityRepository
{
}
