security:
    encoders:
        AppBundle\Entity\User: bcrypt
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN: [ROLE_MODERATOR]
        ROLE_MODERATOR: [ROLE_USER]

    access_denied_url: /login

    providers:

        chin_providers:
            chain:
                providers: [in_memory, user_db]
        in_memory:
            memory:
                users:
                    admin: {password: adminpass, roles: ROLE_ADMIN}
                    admin2: {password: adminpass, roles: ROLE_ADMIN}
                    moderator: {password: moderatorpass, roles: ROLE_MODERATOR}
                    Romich: {password: 123456, roles: ROLE_MODERATOR}
        user_db:
            entity: {class: AppBundle:User, property: username}

    firewalls:
        main:
            pattern: /.*

            form_login:
                login_path: user_login
                check_path: user_login_check
                default_target_path: /

            logout:
                path: user_logout
                target: homepage
            security: true
            anonymous: true

    access_control:
        - { path: ^/login,            allow_if: "not has_role('ROLE_ADMIN')" }
        - { path: ^/registration,     roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin,            roles: ROLE_ADMIN  }
        - { path: ^/create_product/,   roles: IS_AUTHENTICATED_ANONYMOUSLY  }
        - { path: ^/create_product/.*,   roles: IS_AUTHENTICATED_ANONYMOUSLY  }
        - { path: ^/,                 roles: IS_AUTHENTICATED_ANONYMOUSLY }

